server:
  port: 8080
  context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/wechat_pay?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
      default-property-inclusion: non_null
wechat:
  mpAppId: wxf9676f9cb88f48b8
  mpAppSecret: cc24d3836a8d3e0760c766b559767c2d
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://quan.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus:
projectUrl:
  wechatMpAuthorize: http://quan.natapp1.cc
  sell: http://quan.natapp1.cc